package org.cufy.mmrpc.gen.kotlin.context

import org.cufy.mmrpc.CanonicalName
import org.cufy.mmrpc.gen.kotlin.InjectNode

// Generated by ChatGPT 5.2

/**
 * Sorts injection nodes in-place so that fallback execution order
 * respects declared dependencies.
 *
 * A node A depends on node B if A.target is declared by B.declares.
 * In such case, B will appear before A in the list.
 *
 * The resulting order guarantees that calling fallbacks from
 * first to last is safe.
 *
 * This function performs an in-place topological sort.
 *
 * @throws IllegalStateException if a cyclic dependency is detected.
 */
fun sort(list: MutableList<InjectNode<*>>) {
    // index: who declares what
    val declaredBy = mutableMapOf<CanonicalName, MutableList<InjectNode<*>>>()
    for (node in list) {
        for (name in node.declares) {
            declaredBy.getOrPut(name) { mutableListOf() }.add(node)
        }
    }

    // build dependency graph
    val indegree = mutableMapOf<InjectNode<*>, Int>()
    val edges = mutableMapOf<InjectNode<*>, MutableList<InjectNode<*>>>()

    for (node in list) {
        indegree[node] = 0
    }

    for (node in list) {
        val deps =
            node.target
                ?.let { declaredBy[it].orEmpty() }
                .orEmpty()

        for (dep in deps) {
            edges.getOrPut(dep) { mutableListOf() }.add(node)
            indegree[node] = indegree.getValue(node) + 1
        }
    }

    // queue of nodes with no dependencies
    val queue = ArrayDeque<InjectNode<*>>()
    for ((node, degree) in indegree) {
        if (degree == 0) queue.add(node)
    }

    // overwrite list in dependency order
    var index = 0
    while (queue.isNotEmpty()) {
        val node = queue.removeFirst()
        list[index++] = node

        for (next in edges[node].orEmpty()) {
            indegree[next] = indegree.getValue(next) - 1
            if (indegree[next] == 0) {
                queue.add(next)
            }
        }
    }

    if (index != list.size) {
        error("Cyclic fallback dependency detected")
    }
}
